//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Usuario
    {
        public decimal Id { get; set; }

        [Required(ErrorMessage ="El correo es requerido")]
        [DataType(DataType.EmailAddress,ErrorMessage ="El correo proporcionado no es válido")]
        public string Correo { get; set; }

        [DisplayName("Usuario")]
        [Required(ErrorMessage ="Usuario requerido")]
        [StringLength(50,MinimumLength =7,ErrorMessage ="El usuario deberá ser minimo de 7 caracteres")]
        public string Usuario1 { get; set; }

        [Required(ErrorMessage ="Contraseña requerida")]
        [DataType(DataType.Password)]
        [DisplayName("Contraseña")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "La contraseña deberá ser minimo de 10 caracteres")]
        [RegularExpression("(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{10,}", ErrorMessage = "La contraseña no es válida")]
        public string Password { get; set; }

        [Required(ErrorMessage ="Es necesario confirmar la contraseña")]
        [Compare("Password")]
        [DataType(DataType.Password)]
        [DisplayName("Confirma contraseña")]
        [StringLength(50, MinimumLength = 10, ErrorMessage = "La contraseña deberá ser minimo de 10 caracteres")]
        public string ConfirmaPassword { get; set; }

        public Nullable<bool> Estatus { get; set; }

        public string Sexo { get; set; }

        public Nullable<System.DateTime> FechaCreacion { get; set; }

        public string MensajeDeError { get; set; }

    }
}
